# Generated by Django 5.0 on 2024-11-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_lessondocumentmodel_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonnotemodel',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
    ]
