# Generated by Django 5.0 on 2024-12-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfomodel',
            name='mobile_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
