# Generated by Django 5.0 on 2024-12-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_siteinfomodel_mobile_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfomodel',
            name='primary_color',
            field=models.CharField(default='kk', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfomodel',
            name='secondary_color',
            field=models.CharField(default='pp', max_length=255),
            preserve_default=False,
        ),
    ]
