# Generated by Django 5.0 on 2024-12-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0006_schooltypemodel_alter_schoolfindermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfindermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE'), ('combined', 'COMBINED')], max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='schoolfindermodel',
            name='school_type',
        ),
        migrations.AddField(
            model_name='schoolfindermodel',
            name='school_type',
            field=models.ManyToManyField(blank=True, to='admin_site.schooltypemodel'),
        ),
    ]
