# Generated by Django 5.0 on 2024-12-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0007_alter_schoolfindermodel_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfindermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('pending', 'PENDING')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolfindermodel',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
