# Generated by Django 5.0 on 2024-12-19 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0008_schoolfindermodel_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ForumCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('image', models.ImageField(upload_to='images/forum')),
                ('privacy', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('pending', 'PENDING')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/forum')),
                ('description', models.TextField()),
                ('detail', models.TextField()),
                ('privacy', models.BooleanField(blank=True, default=False)),
                ('upvote', models.IntegerField(blank=True, default=0)),
                ('downvote', models.IntegerField(blank=True, default=0)),
                ('vote', models.IntegerField(blank=True, default=0)),
                ('upvoters', models.JSONField(blank=True, default={})),
                ('downvoters', models.JSONField(blank=True, default={})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('pending', 'PENDING')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('privacy', models.BooleanField(blank=True, default=False)),
                ('upvote', models.IntegerField(blank=True, default=0)),
                ('downvote', models.IntegerField(blank=True, default=0)),
                ('vote', models.IntegerField(blank=True, default=0)),
                ('upvoters', models.JSONField(blank=True, default={})),
                ('downvoters', models.JSONField(blank=True, default={})),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('pending', 'PENDING')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='admin_site.forumtagmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ForumAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('privacy', models.BooleanField(blank=True, default=False)),
                ('upvote', models.IntegerField(blank=True, default=0)),
                ('downvote', models.IntegerField(blank=True, default=0)),
                ('vote', models.IntegerField(blank=True, default=0)),
                ('upvoters', models.JSONField(blank=True, default={})),
                ('downvoters', models.JSONField(blank=True, default={})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('pending', 'PENDING')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_site.forumquestionmodel')),
            ],
        ),
    ]
