# Generated by Django 5.0 on 2024-12-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0010_blogcategorymodel_blogtagmodel_blogpostmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumquestionmodel',
            name='privacy',
            field=models.CharField(blank=True, default='public', max_length=20),
        ),
    ]
